#!/usr/bin/env bash
set -e
echo "NeoNet Release Build helper"
echo "1) Start Hardhat node in background:"
echo "   cd contracts/hardhat"
echo "   npm install"
echo "   npx hardhat node &"
echo ""
echo "2) Deploy contracts to local node:"
echo "   npx hardhat run scripts/deploy.js --network localhost"
echo "   Copy addresses printed and set relayer/.env ORACLE_ADDR and RELAYER_KEY"
echo ""
echo "3) Start stack:"
echo "   ./scripts/up.sh"
echo ""
echo "4) Start dApp (optional):"
echo "   cd dapp && npm install && npm run start"
echo ""
echo "Note: This script provides steps rather than automating across environments. For full automation, ensure you have Node, Docker, and Docker Compose available."
